fix: update CD BE

diff --git a/.github/workflows/backend-cd.yml b/.github/workflows/backend-cd.yml
--- a/.github/workflows/backend-cd.yml
+++ b/.github/workflows/backend-cd.yml
@@ -100,3 +100,11 @@ jobs:
           cd k8s
           kustomize edit set image backend=310722232770.dkr.ecr.us-east-1.amazonaws.com/${{env.IMAGE_REPO_NAME}}:${{env.IMAGE_TAG}}
           kustomize build | kubectl apply -f -
+      - name: Verify Deployment Status
+        run: |
+          if kubectl rollout status deployment/backend -n default --timeout=2m | grep -q 'deployment "backend" successfully rolled out'; then
+            echo "Deployment succeeded."
+          else
+            echo "Deployment failed."
+            exit 1
+          fi
